version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: food_tour_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: food_tour_app
      MYSQL_USER: minhngosen196
      MYSQL_PASSWORD: minhngosen196
    ports:
      - "3307:3306"
    volumes:
      - ../FoodTourApp_data:/var/lib/mysql
